### ISSUE TITLE
Roadmap for version 0.1

### ISSUE THREAD

**Issue by JonDotsoy** [JonDotsoy/bert-cli#1]
### Bert.js@0.1

Do easily that work with child_process.

### The new to bert

On this version is possible to do the next features:

- [ ] Use spawn on an async function (With [child_process][], It's is the difference by Callback Vs. Promise function.)
- [ ] Run command on a docker container (use the `agen.sh(<command on a docker container>)` equals to `docker exec container <command>`)
- [ ] Run command on a ssh terminal (Ex. `sshConnection.sh(<my remote commnad>)` equals to `ssh remote <command>`).

[child_process]: https://nodejs.org/api/child_process.html
